SELECT BC.USER_ID,
    BC.PRODUCT_ID
    FROM (
        SELECT USER_ID, PRODUCT_ID, COUNT(USER_ID)
        FROM ONLINE_SALE
        GROUP BY USER_ID, PRODUCT_ID
        HAVING COUNT(USER_ID) >= 2
        ) BC
    ORDER BY BC.USER_ID, BC.PRODUCT_ID DESC;
    
    
