SELECT I.FOOD_TYPE,
    I.REST_ID,
    I.REST_NAME,
    I.FAVORITES
FROM REST_INFO I
JOIN (
    SELECT FOOD_TYPE,
        MAX(FAVORITES) MF
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) M
    ON I.FAVORITES = M.MF AND
    I.FOOD_TYPE = M.FOOD_TYPE
ORDER BY I.FOOD_TYPE DESC



