SELECT ID,
       CASE
            WHEN A.GRADE = 1 THEN 'CRITICAL'
            WHEN A.GRADE = 2 THEN 'HIGH'
            WHEN A.GRADE = 3 THEN 'MEDIUM'
            WHEN A.GRADE = 4 THEN 'LOW'
       END AS COLONY_NAME
FROM (
    SELECT ID,
       NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS GRADE
    FROM ECOLI_DATA
) A
ORDER BY ID;