SELECT II_C.ITEM_ID,
    II_C.ITEM_NAME,
    II_C.RARITY
    FROM ITEM_INFO II_P
    JOIN ITEM_TREE IT 
        ON II_P.ITEM_ID = IT.PARENT_ITEM_ID
    JOIN ITEM_INFO II_C
        ON II_C.ITEM_ID = IT.ITEM_ID
    WHERE II_P.RARITY = 'RARE'
    ORDER BY II_C.ITEM_ID DESC;