SELECT DISTINCT(H.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID AND
    C.CAR_TYPE = '세단'
WHERE MONTH(START_DATE) = 10 
ORDER BY CAR_ID DESC