SELECT FI.ID,
    FN.FISH_NAME,
    FI.LENGTH
FROM FISH_INFO FI
JOIN (
    SELECT ID,
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
) M
    ON FI.FISH_TYPE = M.FISH_TYPE AND
    FI.LENGTH = M.LENGTH
JOIN FISH_NAME_INFO FN
    ON FI.FISH_TYPE = FN.FISH_TYPE
ORDER BY ID;





